config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :skills,  only: [:update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/footprint.rb
class Footprint < ApplicationRecord
  belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  default_scope -> { order(count: :desc) }
  validates :user_id, presence: true
  validates :count, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :skills
  has_many :footprints
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                  format:     { with: VALID_EMAIL_REGEX },
                  uniqueness: { case_sensitive: false }
                  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
   # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  
  private
    def logged_in_user
      unless logged_in?
        #store_location
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create 
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :logged_in_user, only: [:update]
  
  def update
    @skill = Skill.find(params[:id])
    @user = User.find_by(id: @skill.user.id)
    @footprint = Footprint.find_by(user_id: @user.id, footprint_id: current_user.id, skill_id: @skill.id)
    if !!@footprint
      redirect_to user_path(@skill.user_id)
    else
      if @skill.increment!(:count, 1)
        @footprint = @user.footprints.build(footprint_id: current_user.id, skill_id: @skill.id)
        @footprint.save
        redirect_to user_path(@skill.user_id)
      else
        redirect_to user_path(@skill.user_id)
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index]
  
  def index
    @users = User.paginate(page: params[:page])
  end

  
  def show
    @user = User.find(params[:id])
    @skills = @user.skills.all
    @footprints = @user.footprints.all
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # beforeアクション


    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title ="")
    base_title = "Wantedly"
    if page_title.empty?
      base_title
    else
      page_title + " | "+ base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
   # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
   # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end
  
  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size:80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "wantedly skill app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/skills/_skill.html.erb
<% if skill.count > 0  && skill.user == current_user %>
  <ol class="skills">
    <li class="possitive_count",id="skill-<%= skill.id %>">
    <span class="count"><%= skill.count %></span>
    <span class="name1"><%= skill.name %></span>
    </li>
  </ol>
<% elsif skill.count > 0 %>
  <ol class="skills">
    <li class="possitive_count",id="skill-<%= skill.id %>">
    <span class="count"><%= link_to skill.count, skill_path(skill), method: :put %></span>
    <span class="name1"><%= skill.name %></span>
    </li>
  </ol>
<% else %>
  <span class="name2"><%= link_to skill.name, skill_path(skill), method: :put %>, </span>
<% end %>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="center jumbotron">
  <h1 class="help">Help</h1>
  <p>
    <ul>
      <li>ナビゲータのLog inでログインをしてから使います。</li>
      <ul>ユーザ1人目はemail="example@railstutorial.org", password="foobar"</ul>
      <ul>残りのアカウントはemail="example-n@railstutorial.org"(nには0〜100の数字が入る), password="password"</ul>
      <li>1〜20人目のユーザにはスキルページを割り振ってあります(それ以降は割り振っていません)。</li>
      <li>ナビゲータのUsersでユーザ一覧、そこからユーザ個人のプロフィールに進むことができます。自分のプロフィールへはAccount→Profileで進むこともできます。</li>
      <li>並んでいるスキルの名前をクリックすると、クリック数とともにスキル名がリストになって表示されます。</li>
      <li>すでに追加されているスキルは、数字をクリックすることでスキルの回数が増えるようになっています。</li>
    </ul>
  </p>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Wantedly選考課題</h1>
    <h2>
      <a href="https://gist.github.com/luvtechno/10ffa6e8f808cf5d8b4e3073087a08f9">Wantedlyの選考課題</a>
      に関するホームページ。Log inしたのち、Userでユーザ一覧、Profileで自分のプロフィールにいきます
      
      詳しくはHelpにて
      
    </h2>
    
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @skills.any? %>
      <h3>Skills</h3>
        <%= render @skills %>
    <% end %>
  </div>
</div>